heat_template_version: 2018-08-31

description: DoziLab PostgreSQL VM (localhost-only) + optional pgAdmin4 Web UI

parameters:
  stack_label:
    type: string
    description: Short label used in hostname/log markers
    default: "sql"

  image:
    type: string
    description: Glance image name or ID

  flavor:
    type: string
    description: Nova flavor name or ID

  network:
    type: string
    description: Tenant network name or ID

  external_network:
    type: string
    description: External network name or ID for Floating IP

  key_name:
    type: string
    description: Nova keypair name for SSH
    default: "heat-bastion-key"

  ssh_cidr:
    type: string
    description: Allowed CIDR for SSH
    default: "0.0.0.0/0"

  web_cidr:
    type: string
    description: Allowed CIDR for pgAdmin over HTTP (port 80)
    default: "0.0.0.0/0"

  course_spec_b64:
    type: string
    description: Base64-encoded JSON payload for course provisioning (single line, no newlines)

resources:
  secgroup:
    type: OS::Neutron::SecurityGroup
    properties:
      name: { str_replace: { template: "dozilab-pg-__LABEL__", params: { "__LABEL__": { get_param: stack_label } } } }
      description: Security group for DoziLab Postgres+pgAdmin VM
      rules:
        - direction: ingress
          ethertype: IPv4
          protocol: tcp
          port_range_min: 22
          port_range_max: 22
          remote_ip_prefix: { get_param: ssh_cidr }

        - direction: ingress
          ethertype: IPv4
          protocol: tcp
          port_range_min: 80
          port_range_max: 80
          remote_ip_prefix: { get_param: web_cidr }

        # egress allow all (default in many setups; define explicitly to be safe)
        - direction: egress
          ethertype: IPv4

  port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: network }
      security_groups: [ { get_resource: secgroup } ]

  server:
    type: OS::Nova::Server
    properties:
      name: { str_replace: { template: "dozilab-pg-__LABEL__", params: { "__LABEL__": { get_param: stack_label } } } }
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: port }
      user_data_format: RAW
      user_data:
        str_replace:
          template: { get_file: ../cloud-init/user-data.yaml }
          params:
            "__STACK_LABEL__": { get_param: stack_label }
            "__COURSE_SPEC_B64__": { get_param: course_spec_b64 }

  fip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: external_network }

  fip_assoc:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: fip }
      port_id: { get_resource: port }

outputs:
  ssh_user:
    description: SSH username
    value: ubuntu

  floating_ip:
    description: Public Floating IP
    value: { get_attr: [ fip, floating_ip_address ] }

  private_ip:
    description: Private IP on tenant network
    value: { get_attr: [ port, fixed_ips, 0, ip_address ] }

  server_id:
    description: Nova server ID
    value: { get_resource: server }

  pgadmin_url:
    description: pgAdmin4 URL (if enabled)
    value:
      str_replace:
        template: "http://__FIP__/pgadmin4/"
        params:
          "__FIP__": { get_attr: [ fip, floating_ip_address ] }

  ssh_hint:
    description: Admin SSH (key-based)
    value:
      str_replace:
        template: "ssh -i ~/.ssh/heat-bastion-key.pem ubuntu@__FIP__"
        params:
          "__FIP__": { get_attr: [ fip, floating_ip_address ] }

  ssh_tunnel_hint:
    description: How to access Postgres securely via SSH tunnel
    value:
      str_replace:
        template: "ssh -i ~/.ssh/heat-bastion-key.pem -L 5432:127.0.0.1:5432 ubuntu@__FIP__"
        params:
          "__FIP__": { get_attr: [ fip, floating_ip_address ] }

  ready_marker:
    description: Backend should wait until this marker appears in the Nova console log
    value:
      str_replace:
        template: "DOZILAB_READY stack=__LABEL__"
        params:
          "__LABEL__": { get_param: stack_label }
