app:
  name: postgres-group-db
  label: PostgreSQL Group DB
  version: 1.1.0
  description: >
    Provision one Ubuntu VM with PostgreSQL (localhost-only) and optional pgAdmin.
    Creates group databases, student logins, and teacher access. Backend can wait
    for the DOZILAB_READY marker in the Nova console log.
  owner_team: dozilab-app-team

artifacts:
  heat_template: heat/main.yaml
  cloud_init: cloud-init/user-data.yaml

# Parameters exposed to the AppStore UI.
parameters:
  # --- VM basics ---
  - name: stack_label
    label: Label
    step: template
    type: string
    default: "sql"
    required: true
    description: >
      Short course/stack label used in VM name and log markers (e.g. sql-2026-01).
      Must match: ^[a-z0-9][a-z0-9-]{0,30}$

  - name: image
    label: Image
    step: konfiguration
    type: string
    default: "Ubuntu 22.04 2025-01"
    enum:
      - "Ubuntu 22.04 2025-01"
      - "Ubuntu 24.04 2025-01"
      - "Ubuntu 24.04 2026-01"
    required: true
    description: "Base image for the VM (restricted to known good images)."

  - name: flavor
    label: Flavor
    step: konfiguration
    type: string
    default: "gp1.small"
    enum:
      - "gp1.small"
      - "gp1.medium"
    required: true
    description: "VM size. Keep small/medium for student workloads."

  # --- Access control / networking ---
  - name: ssh_cidr
    label: SSH erlaubtes Netz (CIDR)
    step: netzwerk
    type: string
    default: "141.72.0.0/16"
    required: true
    description: >
      IPv4 CIDR allowed to SSH. Default is DHBW/VPN range.
      Examples: 141.72.0.0/16 or 1.2.3.4/32.

  - name: web_cidr
    label: pgAdmin erlaubtes Netz (CIDR)
    step: netzwerk
    type: string
    default: "141.72.0.0/16"
    required: true
    description: "IPv4 CIDR allowed to reach pgAdmin (HTTP port 80)."

  # --- Provisioning payload ---
  - name: course_spec_b64
    label: Course Spec (Base64)
    step: konfiguration
    type: string
    required: true
    description: >
      Base64-encoded JSON for course provisioning (single line, no newlines).
      See postgres_group_db/README.md for the exact JSON schema.

  # --- Platform-fixed parameters (not shown in UI) ---
  - name: network
    label: Internes Netzwerk
    step: netzwerk
    type: string
    default: "NAT"
    hidden: true
    description: "Internal network (fixed)."

  - name: external_network
    label: Externes Netzwerk (Floating IP)
    step: netzwerk
    type: string
    default: "DHBW"
    hidden: true
    description: "External/FloatingIP network (fixed)."

  - name: key_name
    label: Admin SSH-Key
    step: zugriff
    type: string
    default: "heat-bastion-key"
    hidden: true
    description: "Admin/support SSH keypair (fixed)."

outputs:
  - name: ssh_user
    from_heat_output: ssh_user
    description: "SSH username (ubuntu)."

  - name: floating_ip
    from_heat_output: floating_ip
    description: "Public floating IP address."

  - name: private_ip
    from_heat_output: private_ip
    description: "Private IP on tenant network."

  - name: server_id
    from_heat_output: server_id
    description: "Nova server ID (useful for console-log polling)."

  - name: pgadmin_url
    from_heat_output: pgadmin_url
    description: "pgAdmin4 URL (if enabled)."

  - name: ssh_hint
    from_heat_output: ssh_hint
    description: "Admin SSH command template."

  - name: ssh_tunnel_hint
    from_heat_output: ssh_tunnel_hint
    description: "How to access Postgres securely via SSH tunnel."

  - name: ready_marker
    from_heat_output: ready_marker
    description: "Marker string that appears in Nova console log when provisioning is done."
