heat_template_version: 2018-08-31

description: >
  DoziLab Multi-Student VM: Ubuntu VM + Floating IP + password SSH for multiple users.
  Root disk is provisioned as a Cinder volume (Boot from Volume) so "Speicher" can be configured.

parameters:
  image:
    type: string
    default: "Ubuntu 22.04 2025-01"
    constraints:
      - allowed_values:
          - "Ubuntu 22.04 2025-01"
          - "Ubuntu 24.04 2025-01"
          - "Ubuntu 24.04 2026-01"
    description: "Base image for the VM."

  flavor:
    type: string
    default: "gp1.small"
    constraints:
      - allowed_values:
          - "gp1.small"
          - "gp1.medium"
    description: "VM size. Keep small/medium for student workloads."

  # NEW: Root disk size as volume (controls "Speicher" in UI)
  volume_size:
    type: number
    default: 8
    constraints:
      - range: { min: 8, max: 200 }
    description: "Root volume size in GB."

  network:
    type: string
    default: "NAT"
    constraints:
      - allowed_values: ["NAT"]

  external_network:
    type: string
    default: "DHBW"
    constraints:
      - allowed_values: ["DHBW"]

  key_name:
    type: string
    default: "heat-bastion-key"
    constraints:
      - allowed_values: ["heat-bastion-key"]
    description: "Admin/support SSH keypair (später erweiterbar)"

  ssh_cidr:
    type: string
    default: "141.72.0.0/16"
    constraints:
      - allowed_pattern: '^(\d{1,3}\.){3}\d{1,3}/\d{1,2}$'
    description: "IPv4 CIDR allowed to SSH (default DHBW/VPN)."

  user_json:
    type: string
    default: |
      {"course_label":"","instance":{"credentials":[]},"applications":[]}
    description: "Base64-encoded JSON payload (raw JSON also accepted; multi-line allowed)."
    constraints:
      - length: { min: 2 }

  force_password_change:
    type: boolean
    default: true

  workdir:
    type: string
    default: "work"
    constraints:
      - allowed_pattern: '^[A-Za-z0-9._-]{1,32}$'
    description: "Work directory under each user's home (e.g. work)."

  stack_label:
    type: string
    default: "multistudent"
    constraints:
      - allowed_pattern: '^[a-z0-9][a-z0-9-]{0,30}$'
    description: "Internal label used for resource names/metadata."

  pw_min_length:
    type: number
    default: 12
    constraints:
      - range: { min: 4, max: 128 }

  pw_require_digit:
    type: boolean
    default: true

  pw_require_upper:
    type: boolean
    default: true

  pw_require_special:
    type: boolean
    default: true

resources:
  secgroup:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Allow SSH + ICMP (VPN/Campus only)
      rules:
        - direction: ingress
          ethertype: IPv4
          protocol: tcp
          port_range_min: 22
          port_range_max: 22
          remote_ip_prefix: { get_param: ssh_cidr }

        - direction: ingress
          ethertype: IPv4
          protocol: icmp
          remote_ip_prefix: { get_param: ssh_cidr }

  port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: network }
      security_groups:
        - { get_resource: secgroup }

  # NEW: Root volume created from selected image
  root_volume:
    type: OS::Cinder::Volume
    properties:
      name:
        str_replace:
          template: "dozilab-STACK-root"
          params:
            STACK: { get_param: stack_label }
      size: { get_param: volume_size }
      image: { get_param: image }
      metadata:
        dozilab_stack_label: { get_param: stack_label }

  server:
    type: OS::Nova::Server
    properties:
      name:
        str_replace:
          template: "dozilab-STACK"
          params:
            STACK: { get_param: stack_label }

      # image removed: booting from Cinder volume
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }

      block_device_mapping_v2:
        - boot_index: 0
          volume_id: { get_resource: root_volume }
          delete_on_termination: true

      networks:
        - port: { get_resource: port }

      metadata:
        dozilab_stack_label: { get_param: stack_label }
        dozilab_ready_marker: "DOZILAB_READY"

      user_data_format: RAW
      user_data:
        str_replace:
          template: { get_file: ../cloud-init/user-data.yaml }
          params:
            __USER_JSON__:
              str_replace:
                template: { get_param: user_json }
                params:
                  "\n": "\n      "
            __FORCE_CHANGE__: { get_param: force_password_change }
            __WORKDIR__: { get_param: workdir }

            __PW_MIN_LENGTH__: { get_param: pw_min_length }
            __PW_REQUIRE_DIGIT__: { get_param: pw_require_digit }
            __PW_REQUIRE_UPPER__: { get_param: pw_require_upper }
            __PW_REQUIRE_SPECIAL__: { get_param: pw_require_special }

            __STACK_LABEL__: { get_param: stack_label }

  fip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: external_network }

  fip_assoc:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: fip }
      port_id: { get_resource: port }

outputs:
  floating_ip:
    value: { get_attr: [fip, floating_ip_address] }

  server_id:
    description: "Nova server ID (useful for console-log polling)"
    value: { get_resource: server }

  ssh_hint:
    description: "Students login like: ssh <username>@<floating_ip>"
    value:
      str_replace:
        template: "ssh <username>@FIP"
        params:
          FIP: { get_attr: [fip, floating_ip_address] }

  ready_marker:
    description: "Backend should wait until this marker appears in the Nova console log"
    value:
      str_replace:
        template: "DOZILAB_READY stack=STACK"
        params:
          STACK: { get_param: stack_label }

  root_volume_id:
    description: "Cinder root volume ID (debug/traceability)"
    value: { get_resource: root_volume }
