app:
  name: dozilab-multistudent-ubuntu
  version: 1.0.0
  description: >
    Deploy one Ubuntu VM for a course with multiple local student accounts (username/password),
    SSH allowed only from DHBW/VPN CIDR, and a Floating IP on DHBW.
    Backend can wait for DOZILAB_READY marker in the Nova console log.
  owner_team: dozilab-app-team

artifacts:
  heat_template: heat/main.yaml
  cloud_init: cloud-init/user-data.yaml

# Parameters exposed to the AppStore UI.
# Keep only what is meaningful for users; platform-fixed settings are hidden or fixed via allowed_values in Heat.
parameters:
  # --- VM basics ---
  - name: stack_label
    type: string
    default: multistudent
    required: true
    description: >
      Short course/stack label used in VM name and metadata (e.g. kurs-01).
      Must match: ^[a-z0-9][a-z0-9-]{0,30}$

  - name: image
    type: string
    default: "Ubuntu 22.04 2025-01"
    enum:
      - "Ubuntu 22.04 2025-01"
      - "Ubuntu 24.04 2025-01"
      - "Ubuntu 24.04 2026-01"
    required: true
    description: "Base image for the VM (restricted to known good images)."

  - name: flavor
    type: string
    default: "gp1.small"
    enum:
      - "gp1.small"
      - "gp1.medium"
    required: true
    description: "VM size. Keep small/medium for student workloads."

  # --- Access control / networking ---
  - name: ssh_cidr
    type: string
    default: "141.72.0.0/16"
    required: true
    description: >
      IPv4 CIDR allowed to SSH and ICMP (ping). Default is DHBW/VPN range.
      Examples: 141.72.0.0/16 (VPN/Campus) or 1.2.3.4/32 (single IP).

  # --- Student accounts (secret) ---
  - name: students
    type: string
    secret: true
    required: true
    description: >
      JSON string mapping username -> password.
      Example: {"alice":"pw","bob":"pw2"} (must use double quotes).

  - name: force_password_change
    type: boolean
    default: true
    required: true
    description: "If true, student users must change their password on first login."

  - name: workdir
    type: string
    default: "work"
    required: true
    description: "Directory created under each student's home and used as default login directory."

  # --- Password policy (showcase / configurable in V1) ---
  - name: pw_min_length
    type: number
    default: 12
    required: true
    description: "Minimum password length enforced via PAM pwquality."

  - name: pw_require_digit
    type: boolean
    default: true
    required: true
    description: "Require at least one digit."

  - name: pw_require_upper
    type: boolean
    default: true
    required: true
    description: "Require at least one uppercase letter."

  - name: pw_require_special
    type: boolean
    default: true
    required: true
    description: "Require at least one special character."

  # --- Platform-fixed parameters (not shown in UI) ---
  # Heat enforces allowed_values for these anyway. Keeping them hidden avoids confusion.
  - name: network
    type: string
    default: "NAT"
    hidden: true
    description: "Internal network (fixed)."

  - name: external_network
    type: string
    default: "DHBW"
    hidden: true
    description: "External/FloatingIP network (fixed)."

  - name: key_name
    type: string
    default: "heat-bastion-key"
    hidden: true
    description: "Admin/support SSH keypair (fixed in v1)."

outputs:
  - name: floating_ip
    from_heat_output: floating_ip
    description: "Public floating IP address."

  - name: server_id
    from_heat_output: server_id
    description: "Nova server ID (useful for console-log polling)."

  - name: ssh_hint
    from_heat_output: ssh_hint
    description: "How students login (template string)."

  - name: ready_marker
    from_heat_output: ready_marker
    description: "Marker string that appears in Nova console log when provisioning is done. Also nach was müsst ihr im log ausschau halten dass ihr wisst dass die VM Ready ist"
