heat_template_version: 2018-08-31

description: >
  DoziLab Multi-Student VM: Ubuntu VM + Floating IP + password SSH for multiple users.

parameters:
  image:
    type: string
    default: "Ubuntu 22.04 2025-01"

  flavor:
    type: string
    default: "gp1.small"

  network:
    type: string
    default: "NAT"

  external_network:
    type: string
    default: "DHBW"

  key_name:
    type: string
    default: "heat-bastion-key"

  ssh_cidr:
    type: string
    default: "0.0.0.0/0"

  students:
    type: json
    description: "Map of username -> password. Example: { alice: 'pw', bob: 'pw2' }"
    hidden: true

  force_password_change:
    type: boolean
    default: true

  workdir:
    type: string
    default: "work"

  stack_label:
    type: string
    default: "multistudent"


resources:
  secgroup:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Allow SSH + HTTP + ICMP
      rules:
        - direction: ingress
          ethertype: IPv4
          protocol: tcp
          port_range_min: 22
          port_range_max: 22
          remote_ip_prefix: { get_param: ssh_cidr }
        - direction: ingress
          ethertype: IPv4
          protocol: tcp
          port_range_min: 80
          port_range_max: 80
          remote_ip_prefix: 0.0.0.0/0
        - direction: ingress
          ethertype: IPv4
          protocol: icmp
          remote_ip_prefix: 0.0.0.0/0

  port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: network }
      security_groups:
        - { get_resource: secgroup }

  server:
    type: OS::Nova::Server
    properties:
      name:
        str_replace:
          template: "dozilab-STACK"
          params:
            STACK: { get_param: stack_label }

      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }

      networks:
        - port: { get_resource: port }

      user_data_format: RAW
      user_data:
        str_replace:
          template: { get_file: cloud-init.yaml }
          params:
            __STUDENTS_JSON__: { get_param: students }
            __FORCE_CHANGE__: { get_param: force_password_change }
            __WORKDIR__: { get_param: workdir }


  fip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: external_network }

  fip_assoc:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: fip }
      port_id: { get_resource: port }

outputs:
  floating_ip:
    value: { get_attr: [fip, floating_ip_address] }

  ssh_hint:
    description: "Students login like: ssh <username>@<floating_ip>"
    value:
      str_replace:
        template: "ssh <username>@FIP"
        params:
          FIP: { get_attr: [fip, floating_ip_address] }

